// Data used for testing html injection functions

const SPORT_LEAGUES = {
    'football': [
        'serie a',
        'premier league',
        'la liga',
        'champions league'
    ],
    'basket': [
        'nba'
    ],
    'hockey': [
        'nhl'
    ]
};

const LEAGUE_TEAMS = {

    'serie a' : [
        'AC Milan',
        'Atalanta',
        'Bologna',
        'Cagilari',
        'Chievo',
        'Crotone',
        'Empoli',
        'Fiorentina',
        'Genoa',
        'Inter Milan',
        'Juventus',
        'Lazio',
        'Napoli',
        'Palermo',
        'Pescara',
        'Roma',
        'Sampdoria',
        'Sassuolo',
        'Torino',
        'Udinese'
    ],

    'premier league' : [
        'Arsenal',
        'Bournemouth',
        'Burnley',
        'Chelsea',
        'Crystal Palace',
        'Everton',
        'Hull City',
        'Leicester City',
        'Liverpool',
        'Manchester City',
        'Manchester United',
        'Middlesbrough',
        'Southampton',
        'Stoke City',
        'Sunderland',
        'Swansea City',
        'Tottenham Hotspur',
        'Watford',
        'West Bromwich Albion',
        'West Ham United'
    ],

    'la liga' : [
        'Alaves',
        'Athletic Bilbao',
        'Atletico Madrid',
        'Barcelona',
        'CA Osasuna',
        'CD Leganes',
        'Celta Vigo',
        'Deportivo La Coruna',
        'Eibar',
        'Espanyol',
        'Granada',
        'Las Palmas',
        'Malaga',
        'Real Betis',
        'Real Madrid',
        'Real Sociedad',
        'Sevilla',
        'Sporting Gijon',
        'Valencia',
        'Villarreal'
    ],

    'champions league' : [
        'Arsenal',
        'Atletico Madrid',
        'Barcelona',
        'Bayer Leverkusen',
        'Bayern Munich',
        'Borussia Dortmund',
        'Celtic',
        'Juventus',
        'Leicester City',
        'Lyon',
        "M'gladbach",
        'Manchester City',
        'Monaco',
        'Napoli',
        'PSV Eindhoven',
        'Paris Saint-Germain',
        'Real Madrid',
        'Sevilla',
        'Tottenhaum Hotspur'
    ],

    'nba' : [
        'Boston Celtics',
        'Brooklyn Nets',
        'New York Knicks',
        'Philadelphia 76ers',
        'Toronto Raptors',
        'Chicago Bulls',
        'Cleveland Cavaliers',
        'Detroit Pistons',
        'Indiana Pacers',
        'Milwaukee Bucks',
        'Atlanta Hawks',
        'Charlotte Hornets',
        'Miami Heat',
        'Orlando Magic',
        'Washington Wizards',
        'Dallas Mavericks',
        'Houston Rockets',
        'Memphis Grizzlies',
        'New Orleans Pelicans',
        'San Antonia Spurs',
        'Denver Nuggets',
        'Minnesota Timberwolves',
        'Oklahoma City Thunder',
        'Portland Trail Blazers',
        'Utah Jazz',
        'Golden State Warriors',
        'LA Clippers',
        'Log Angeles Lakers',
        'Phoenix Suns',
        'Sacramento Kings',
    ],

    'nhl' : [
        'Anaheim Ducks',
        'Arizona Coyotes',
        'Boston Bruins',
        'Buffalo Sabres',
        'Calgary Flames',
        'Carolina Hurricanes',
        'Chicago Blackhawks',
        'Colorado Avalanche',
        'Columbus Blue Jackets',
        'Dallas Stars',
        'Detroit Red Wings',
        'Edmonton Oilers',
        'Florida Panthers',
        'Los Angeles Kings',
        'Minnesota Wild',
        'Montréal Canadiens',
        'Nashville Predators',
        'New Jersey Devils',
        'New York Islanders',
        'New York Rangers',
        'Ottawa Senators',
        'Philadelphia Flyers',
        'Pittsburgh Penguins',
        'San Jose Sharks',
        'St. Louis Blues',
        'Tampa Bay Lightning',
        'Toronto Maple Leafs',
        'Vancouver Canucks',
        'Washington Capitals',
        'Winnipeg Jets'
    ],
};


